import { ReactNode } from 'react';
import './global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <p className='text-red-800'>okokok</p>
        {children}</body>
    </html>
  );
}
