name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - chore/update-ci

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm nx run-many --target=build --affected
      - name: Run tests
        run: |
          pnpm nx run-many --target=test --affected
