name: CI/CD Workflow

on:
 pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies and build
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm nx run-many --target=build --affected

      - name: Run tests
        run: |
          pnpm nx run-many --target=test --affected
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Droplet
        # if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          ssh vadhe@159.223.63.200 'cd /var/www/devlinks/ && git pull && pnpm install && pnpm nx build web && cd /var/www/devlinks/dist/packages/web && pnpm install && pm2 restart devlinks'
